services:
  postgres:
    image: postgres:16
    container_name: pulse-dev-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12380
      POSTGRES_DB: pulse-dev
    ports:
      - "3003:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes: 
  postgres-data: